# 异常

## 存在的意义

程序运行过程中，事先对可能发生异常的地方进行处理，可以用 try - catch - finally 语句，类似于 if - else 的判断语句。当实际产生异常时，程序仍然能够继续运行并打印出异常信息，方便排查。也可以直接抛出产生的异常，将这种异常情况层层上报，如果中途一直没有机制处理，则最终由 JVM 内置的处理机制抛出异常。

这套处理异常的机制使得程序产生问题时能够更快更好的解决，这也是其存在的意义。

![1572662724903.png](04-%E5%BC%82%E5%B8%B8.assets/1572662724903.png)

## throw 和 throws 的区别

`throw new RuntimeException();` 语句之后的代码无法再运行，此时 Eclipse 会显示 `Unreachable code` 错误。

在 FileInputStream 的构造方法中可以看到，该方法抛出了一个异常，可以有两种处理方式：一是在调用该方法的另一个方法继续 throws FileNotFoundException，二是使用 try-catch 语句处理异常。

```java
/*FileInputStream.java*/
public FileInputStream(String name) throws FileNotFoundException {
    this(name != null ? new File(name) : null);
}

_09_reflect.carcar.junit.PersonTest.java*/
public static void main(String[] args) throws FileNotFoundException {
    new FileInputStream("d:/test");
}

public static void main(String[] args) {
    try {
    	new FileInputStream("d:/test");    
	} catch(FileNotFoundException e){
        e.printStackTrace();
    }
}
```

```java
public class _09_reflect.car.junit.PersonTest {
	public static void main(String[] args) throws RuntimeException,Exception {	
		throw new RuntimeException();	
	}
}
```

综合：可以看到 throw 之后跟的是**一个异常对象**，而 throws 之后跟的是**一个或多个异常类名**。